name: Release to itch.io

on:
  push:
    tags:
    - 'v*'

env:
  ITCH_USER_NAME: heartbitinteractive
  ITCH_GAME_NAME: the-cheaps
  PROJECT_PATH: Code/TheCheaps

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame

    steps:
    - run: echo  "The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo  "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo  "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Get version from tag
      run: |
        TAGVERSION=$(git describe --tags --abbrev=0)
        echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV    
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Show Working Dir tree BEFORE
      run: |
       echo  "Current work dir is : "
       pwd
       sudo apt-get install tree
       tree -d
       #~ - name: Checkout submodules
       #~ uses: textbook/git-checkout-submodule-action@master      
    - name: Try to update submodule manually to check if permissions are ok afterwards
      run: |
       git submodule update --init --recursive
       echo  "Current work dir is : "
       pwd
       tree -d
       ls -ld Code/Libraries/Lidgren
       #~ chmod -R 777 Code/Libraries/Lidgren
       ls -ld Code/Libraries/Lidgren/Lidgren.Network.MultiTarget
       #~ chmod -R 777 Code/Libraries/Lidgren/Lidgren.Network.MultiTarget       
       mkdir Code/Libraries/Lidgren/Lidgren.Network.MultiTarget/obj 
       mkdir Code/Libraries/Lidgren/Lidgren.Network.MultiTarget/bin
       #~ ls -ld Code/Libraries/Lidgren/Lidgren.Network.MultiTarget/obj
       #~ chmod -R 777 Code/Libraries/Lidgren/Lidgren.Network.MultiTarget/obj 
       #~ ls -ld Code/Libraries/Lidgren/Lidgren.Network.MultiTarget/bin
       #~ chmod -R 777 Code/Libraries/Lidgren/Lidgren.Network.MultiTarget/bin
    - name: Install font
      run: |
        wget -P /usr/share/fonts/truetype https://github.com/Heartbit-Interactive/MGJam2021/raw/main/Assets/Pixellari.ttf
    - name: Setup Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        sudo apt install software-properties-common
        sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
        wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add -
        sudo sh -c 'echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./" > /etc/apt/sources.list.d/obs.list'
        sudo apt update
        sudo apt-get install --install-recommends winehq-stable
        wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/develop/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh
    - name: Build Windows
      run: dotnet publish ${{ env.PROJECT_PATH }} -r win-x64 -c Release --output build-windows
    - name: Build Osx
      run: dotnet publish ${{ env.PROJECT_PATH }} -r osx-x64 -c Release --output build-osx
    - name: Build Linux
      run: dotnet publish ${{ env.PROJECT_PATH }} -r linux-x64 -c Release --output build-linux
    - name: Publish Windows build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: windows
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: build-windows
        VERSION: ${{ env.TAGVERSION }}
    - name: Publish OSX build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: osx
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: build-osx
        VERSION: ${{ env.TAGVERSION }}
    - name: Publish Linux build to itch.io
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: linux
        ITCH_GAME: ${{ env.ITCH_GAME_NAME }}
        ITCH_USER: ${{ env.ITCH_USER_NAME }}
        PACKAGE: build-linux
        VERSION: ${{ env.TAGVERSION }}